//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.View.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class medecines_availability
    {
        public int id_medecines_availability { get; set; }
        public string amount_of_medecines { get; set; }
        public Nullable<int> medecines_id_medecines { get; set; }
        public Nullable<int> adresses_id_adresses { get; set; }
    
        public virtual adresses adresses { get; set; }
        public virtual medicines medicines { get; set; }
    }
}
