//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.View.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordered_medecines
    {
        public int id_ordered_medecines { get; set; }
        public Nullable<int> orders_id_orders { get; set; }
        public Nullable<int> medicines_id_medicines { get; set; }
        public Nullable<int> selected_medecines_amount { get; set; }
    
        public virtual medicines medicines { get; set; }
        public virtual orders orders { get; set; }
    }
}
