//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.View.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders()
        {
            this.ordered_medecines = new HashSet<ordered_medecines>();
        }
    
        public int id_orders { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<int> user_id_user { get; set; }
        public string order_time { get; set; }
        public string order_sum { get; set; }
        public Nullable<int> adresses_id_adresses { get; set; }
        public Nullable<int> medecines_id_medecines { get; set; }
        public Nullable<int> customers_id_customers { get; set; }
        public string medecines_list { get; set; }
    
        public virtual adresses adresses { get; set; }
        public virtual customers customers { get; set; }
        public virtual medicines medicines { get; set; }
        public virtual user user { get; set; }
        public virtual customers customers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordered_medecines> ordered_medecines { get; set; }
    }
}
