//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.View.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pharmasyEntities : DbContext
    {
        public pharmasyEntities()
            : base("name=pharmasyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adresses> adresses { get; set; }
        public virtual DbSet<building> building { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<medicines> medicines { get; set; }
        public virtual DbSet<medicines_photo> medicines_photo { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<providers> providers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<medecines_availability> medecines_availability { get; set; }
        public virtual DbSet<photo> photo { get; set; }
        public virtual DbSet<ordered_medecines> ordered_medecines { get; set; }
    }
}
